name: Build Docker using Shared Workflow

on:
  workflow_dispatch:
    inputs:
      dry_run:
        description: 'Dry run'
        type: boolean
        required: true
        default: true
  schedule:
    - cron: '5 20 * * 2' # Runs at 20:05, only on Tuesday

concurrency:
  group: ${{ github.repository }}
  cancel-in-progress: true

jobs:
  call-shared-workflow:
    permissions:
      contents: read
      packages: write
    uses: ggrandes/shared-workflows/.github/workflows/docker.yml@v1
    with:
      dry_run: ${{ github.event_name == 'workflow_dispatch' && inputs.dry_run || false }}
      platforms: |
        linux/amd64
        linux/386
        linux/arm64
        linux/arm/v7
        linux/arm/v6
        linux/riscv64
        linux/ppc64le
        linux/s390x
    secrets:
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}

  internal-registry:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    needs: [call-shared-workflow]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: 'internal'
      - name: Update registry file
        if: success()
        run: |
          set -ex
          date -Is >> .control/registry.txt
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git config user.name 'github-actions[bot]' 
          git commit -a -m "update"
          git push

# END #
